Repository operator-framework/olm-docs, pull requests merged in 2021-09, with the labels that each got.

#181 Fix typo
  content/en/docs/getting-started/_index.md
Labels: lgtm, ok-to-test, approved

#177 Initial docs for file-based catalogs
  content/en/docs/Concepts/olm-architecture/operator-catalog/creating-an-update-graph.md
  content/en/docs/Reference/file-based-catalogs.md
  content/en/docs/Tasks/creating-an-index.md
  content/en/docs/advanced-tasks/communicating-operator-conditions-to-olm.md
  content/en/docs/contribution-guidelines/upgrade-graphs.md
Labels: lgtm, approved

#174 content/en: Minor updates to the deprecated API troubleshooting documentation
  content/en/docs/Tasks/Troubleshooting/subscription.md
Labels: lgtm, approved

#185 cut new v0.18.z release
  config.toml
Labels: approved

#179 .github/workflow: Remove unneeded submodule checkout step
  .github/workflows/lint.yaml
Labels: lgtm, approved

#186 Clean up owners
  OWNERS
Labels: lgtm, approved

#190 Add redirection from latest to v0.18.z
  content/en/docs/Concepts/olm-architecture/operator-catalog/creating-an-update-graph.md
  content/en/docs/Tasks/creating-a-catalog.md
  content/en/docs/Tasks/make-catalog-available-on-cluster.md
Labels: lgtm, approved

#189 Remove not referenced Subscription custom resource
  content/en/docs/Concepts/crds/operatorcondition.md
Labels: lgtm, approved
