Repository operator-framework/olm-docs, pull requests merged in 2021-03, with the labels that each got.

#110 chore(owners): add sdk folks to review/approve
  OWNERS
Labels: do-not-merge/invalid-owners-file

#115 Define an operator for OLM and SDK -- OSDK1656
  content/en/docs/Reference/operator.md
Labels: lgtm

#118 OSDK 1641 -- test package before shipping
  content/en/docs/Tasks/test-package-before-shipping.md
Labels: lgtm

#114 OLM N+1 Update Guide
  content/en/docs/Tasks/images/catalogsource.png
  content/en/docs/Tasks/images/channels.png
  content/en/docs/Tasks/update-operator-to-next-version.md
Labels: lgtm

#121 doc: add Channel Naming
  content/en/docs/Glossary/_index.md
  content/en/docs/best-practices/_index.md
  content/en/docs/best-practices/channel-naming.md
  content/en/docs/best-practices/images/channel-naming1.png
  content/en/docs/best-practices/images/channel-naming2.png
Labels: lgtm

#120 .github: Update the linting workflow check
  .github/workflows/lint.yaml
Labels: lgtm

#99 *: Address markdown linting violations in various documentation files
  README.md
  content/en/docs/Concepts/crds/CatalogSource.md
  content/en/docs/Concepts/crds/_index.md
  content/en/docs/Concepts/crds/clusterserviceversion.md
  content/en/docs/Concepts/crds/operatorgroup.md
  content/en/docs/Concepts/olm-architecture/_index.md
  content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
  content/en/docs/Concepts/olm-architecture/operator-registry/_index.md
  content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
  content/en/docs/Concepts/olm-architecture/operator-registry/using-a-catalog-locally.md
  content/en/docs/Concepts/olm-architecture/operator-registry/using-catalog-with-olm.md
  content/en/docs/Glossary/_index.md
  content/en/docs/Tasks/Troubleshooting/_index.md
  content/en/docs/Tasks/Troubleshooting/catalogsource.md
  content/en/docs/Tasks/Troubleshooting/clusterserviceversion.md
  content/en/docs/Tasks/Troubleshooting/olm-and-catalog-operators.md
  content/en/docs/Tasks/Troubleshooting/subscription.md
  content/en/docs/Tasks/_index.md
  content/en/docs/Tasks/creating-operator-manifests.md
  content/en/docs/Tasks/install-operator-with-olm.md
  content/en/docs/Tasks/list-operators-available-to-install.md
  content/en/docs/Tasks/make-operator-part-of-catalog.md
  content/en/docs/Tasks/uninstall-olm.md
  content/en/docs/Tasks/uninstall-operator.md
  content/en/docs/Tasks/validate-package.md
  content/en/docs/advanced-tasks/_index.md
  content/en/docs/advanced-tasks/communicating-operator-conditions-to-olm.md
  content/en/docs/advanced-tasks/operator-scoping-with-operatorgroups.md
  content/en/docs/advanced-tasks/ship-operator-supporting-multiarch.md
  content/en/docs/contribution-guidelines/_index.md
  content/en/docs/getting-started/_index.md
Labels: lgtm

#109 Add operator bundle creation doc
  content/en/docs/Tasks/creating-operator-bundle.md
  content/en/docs/Tasks/creating-operator-manifests.md
Labels: lgtm

#138 Update make-operator-part-of-catalog.md
  content/en/docs/Tasks/make-operator-part-of-catalog.md
Labels: approved, lgtm

#134 doc: add common suggestions
  content/en/docs/best-practices/common.md
Labels: approved, lgtm

#135 modified the Introduction and added few more points -- OLM #111
  content/en/docs/_index.md
Labels: approved, lgtm
