Repository operator-framework/olm-docs, pull requests merged in 2021-12, with the labels that each got.

#195 Fix typo in docs for creating a catalog
  content/en/docs/Tasks/creating-a-catalog.md
Labels: lgtm, ok-to-test, approved

#193 fix typo in dependency resolution docs
  content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
Labels: lgtm, ok-to-test, approved

#214 Add catalog pod scheduling config documentation
  content/en/docs/advanced-tasks/overriding-catalog-source-pod-scheduling-configuration.md
  content/en/docs/best-practices/channel-naming.md
Labels: lgtm, approved

#218 Introduce OLM Configuration Document
  content/en/docs/advanced-tasks/configuring-olm.md
Labels: lgtm
