Repository operator-framework/olm-docs, pull requests merged in 2023-03, with the labels that each got.

#266 Fix typo in channel naming
  content/en/docs/best-practices/channel-naming.md
Labels: lgtm

#264 Use correct table heading for resource owner
  content/en/docs/Concepts/olm-architecture/_index.md
Labels: lgtm, approved

#250 Add Subscription affinity configuration documentation
  content/en/docs/advanced-tasks/overriding-operator-pod-affinity-configuration.md
Labels: approved

#280 Fixes two minor visual issues in the docs site
  assets/scss/_global.scss
  assets/scss/_homepage.scss
Labels: approved

#283 Switches to `.RelPermalink` from `.URL`
  layouts/partials/navbar.html
Labels: approved
